"""Disposable PostgreSQL schema for shadow adapter contract tests only."""

from __future__ import annotations

import os
from contextlib import asynccontextmanager
from pathlib import Path
from uuid import uuid4

import pytest
from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine, create_async_engine

DDL = (
    "CREATE TABLE brain_source_objects (provider text NOT NULL, account_id text NOT NULL, "
    "object_type text NOT NULL, external_id text NOT NULL, active_generation bigint, "
    "source_head_revision text, PRIMARY KEY(provider,account_id,object_type,external_id))",
    "CREATE TABLE brain_revisions (provider text NOT NULL, account_id text NOT NULL, "
    "object_type text NOT NULL, external_id text NOT NULL, revision text NOT NULL, "
    "content_hash text NOT NULL, received_at timestamptz NOT NULL, "
    "required_scope text NOT NULL, deleted boolean NOT NULL, previous_revision text, "
    "PRIMARY KEY(provider,account_id,object_type,external_id,revision))",
    "CREATE TABLE brain_generations (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
    "provider text NOT NULL, account_id text NOT NULL, object_type text NOT NULL, "
    "external_id text NOT NULL, revision text NOT NULL, extraction_version text NOT NULL, "
    "known_from timestamptz NOT NULL, known_to timestamptz, "
    "UNIQUE(provider,account_id,object_type,external_id,revision,extraction_version))",
    "CREATE TABLE brain_claims (generation_id bigint NOT NULL, ordinal integer NOT NULL, "
    "subject text NOT NULL, predicate text NOT NULL, value text NOT NULL, "
    "valid_from timestamptz NOT NULL, valid_to timestamptz, evidence_anchor text NOT NULL, "
    "evidence_kind text NOT NULL, PRIMARY KEY(generation_id,ordinal))",
    "CREATE TABLE brain_checkpoints (provider text NOT NULL, account_id text NOT NULL, "
    "cursor text, PRIMARY KEY(provider,account_id))",
    "CREATE TABLE brain_rollback_audit (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
    "provider text NOT NULL, account_id text NOT NULL, object_type text NOT NULL, "
    "external_id text NOT NULL, from_generation bigint NOT NULL, "
    "target_generation bigint NOT NULL, restored_generation bigint NOT NULL, "
    "known_at timestamptz NOT NULL, reason text NOT NULL)",
    "CREATE TABLE brain_event_links (event_id bigint PRIMARY KEY, provider text NOT NULL, "
    "account_id text NOT NULL, object_type text NOT NULL, external_id text NOT NULL, "
    "UNIQUE(provider,account_id,object_type,external_id))",
    "CREATE TABLE brain_derived_cache (provider text NOT NULL, account_id text NOT NULL, "
    "cache_key text NOT NULL, payload jsonb NOT NULL, PRIMARY KEY(provider,account_id,cache_key))",
)


def sample_source(
    revision: str = "1", external_id: str = "42", account: str = "owner-a"
):
    from vera_shared.ingest.shadow_types import SourceRevision

    return SourceRevision(
        provider="telegram",
        account_id=account,
        object_type="message",
        external_id=external_id,
        revision=revision,
        content_hash=f"hash-{revision}-{external_id}",
        received_at=f"2026-10-03T00:00:0{revision}Z",
        required_scope=f"telegram:{account}",
        previous_revision=str(int(revision) - 1) if revision != "1" else None,
    )


def sample_claim(value: str = "ship", version: str = "extract-1"):
    from vera_shared.ingest.shadow_types import Claim

    return Claim(
        subject="project",
        predicate="decision",
        value=value,
        valid_from="2026-10-02T12:00:00Z",
        evidence_anchor="message:0-4",
        evidence_kind="document",
        extraction_version=version,
    )


async def use_schema(conn: AsyncConnection, schema: str) -> None:
    await conn.execute(text(f'SET search_path TO "{schema}"'))
    await conn.commit()


@asynccontextmanager
async def isolated_shadow_schema():
    raw_url = os.environ.get("TEST_DATABASE_URL")
    if not raw_url:
        pytest.fail("RUN_INTEGRATION_TESTS=1 requires TEST_DATABASE_URL")
    url = make_url(raw_url)
    if url.get_backend_name() != "postgresql" or url.host not in {
        "localhost",
        "127.0.0.1",
    }:
        pytest.fail("shadow integration requires local isolated PostgreSQL")
    if not url.database or "test" not in url.database.lower():
        pytest.fail("shadow integration refuses a non-test database")
    schema = f"shadowtest_{uuid4().hex}"
    engine: AsyncEngine = create_async_engine(raw_url)
    try:
        async with engine.begin() as conn:
            await conn.execute(text(f'CREATE SCHEMA "{schema}"'))
            await conn.execute(text(f'SET search_path TO "{schema}"'))
            for statement in DDL:
                await conn.execute(text(statement))
        yield engine, schema
    finally:
        async with engine.begin() as conn:
            await conn.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        await engine.dispose()


async def run_migration_sql(conn: AsyncConnection, path: Path) -> None:
    sql = "\n".join(
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if not line.lstrip().startswith("--")
    )
    for statement in sql.split(";"):
        statement = statement.strip()
        if statement and statement not in {"BEGIN", "COMMIT"}:
            await conn.execute(text(statement))


@asynccontextmanager
async def isolated_migrated_shadow_schema():
    raw_url = os.environ.get("TEST_DATABASE_URL")
    if not raw_url:
        pytest.fail("RUN_INTEGRATION_TESTS=1 requires TEST_DATABASE_URL")
    url = make_url(raw_url)
    if url.get_backend_name() != "postgresql" or url.host not in {
        "localhost",
        "127.0.0.1",
    }:
        pytest.fail("shadow integration requires local isolated PostgreSQL")
    if not url.database or "test" not in url.database.lower():
        pytest.fail("shadow integration refuses a non-test database")
    schema = f"shadowmig_{uuid4().hex}"
    engine = create_async_engine(raw_url)
    migration = (
        Path(__file__).resolve().parents[2] / "infra/migrations/047_shadow_brain.sql"
    )
    try:
        async with engine.begin() as conn:
            await conn.execute(text(f'CREATE SCHEMA "{schema}"'))
            await conn.execute(text(f'SET search_path TO "{schema}"'))
            await conn.execute(
                text(
                    "CREATE TABLE events(id bigint PRIMARY KEY,source text,source_event_id text,"
                    "account text,content_text text,metadata jsonb)"
                )
            )
            await conn.execute(
                text(
                    "CREATE TABLE schema_migrations(version text PRIMARY KEY,note text)"
                )
            )
            await conn.execute(
                text(
                    "CREATE TABLE instagram_sessions(username text PRIMARY KEY,is_active boolean NOT NULL)"
                )
            )
            await run_migration_sql(conn, migration)
        yield engine, schema
    finally:
        async with engine.begin() as conn:
            await conn.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        await engine.dispose()
