"""Disposable PostgreSQL schema for shadow adapter contract tests only."""

from __future__ import annotations

import os
from contextlib import asynccontextmanager
from pathlib import Path
from uuid import uuid4

import pytest
from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import AsyncConnection, create_async_engine


def sample_source(
    revision: str = "1", external_id: str = "42", account: str = "owner-a"
):
    from vera_shared.ingest.shadow_types import SourceRevision

    return SourceRevision(
        provider="telegram",
        account_id=account,
        object_type="message",
        external_id=external_id,
        revision=revision,
        content_hash=f"hash-{revision}-{external_id}",
        received_at=f"2026-10-03T00:00:0{revision}Z",
        required_scope=f"telegram:{account}",
        previous_revision=str(int(revision) - 1) if revision != "1" else None,
    )


def sample_claim(value: str = "ship", version: str = "extract-1"):
    from vera_shared.ingest.shadow_types import Claim

    return Claim(
        subject="project",
        predicate="decision",
        value=value,
        valid_from="2026-10-02T12:00:00Z",
        evidence_anchor="message:0-4",
        evidence_kind="document",
        extraction_version=version,
    )


async def use_schema(conn: AsyncConnection, schema: str) -> None:
    await conn.execute(text(f'SET search_path TO "{schema}"'))
    await conn.commit()


@asynccontextmanager
async def isolated_shadow_schema():
    async with isolated_migrated_shadow_schema() as resources:
        yield resources


async def run_migration_sql(conn: AsyncConnection, path: Path) -> None:
    sql = "\n".join(
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if not line.lstrip().startswith("--")
    )
    for statement in sql.split(";"):
        statement = statement.strip()
        if statement and statement not in {"BEGIN", "COMMIT"}:
            await conn.execute(text(statement))


@asynccontextmanager
async def isolated_migrated_shadow_schema():
    raw_url = os.environ.get("TEST_DATABASE_URL")
    if not raw_url:
        pytest.fail("RUN_INTEGRATION_TESTS=1 requires TEST_DATABASE_URL")
    url = make_url(raw_url)
    if url.get_backend_name() != "postgresql" or url.host not in {
        "localhost",
        "127.0.0.1",
    }:
        pytest.fail("shadow integration requires local isolated PostgreSQL")
    if not url.database or "test" not in url.database.lower():
        pytest.fail("shadow integration refuses a non-test database")
    schema = f"shadowmig_{uuid4().hex}"
    engine = create_async_engine(raw_url)
    migration = (
        Path(__file__).resolve().parents[2] / "infra/migrations/047_shadow_brain.sql"
    )
    delivery_migration = (
        Path(__file__).resolve().parents[2] / "infra/migrations/048_shadow_delivery.sql"
    )
    gmail_migration = (
        Path(__file__).resolve().parents[2]
        / "infra/migrations/049_gmail_shadow_pilot.sql"
    )
    protocol_migration = (
        Path(__file__).resolve().parents[2]
        / "infra/migrations/050_gmail_protocol_simulator.sql"
    )
    try:
        async with engine.begin() as conn:
            await conn.execute(text(f'CREATE SCHEMA "{schema}"'))
            await conn.execute(text(f'SET search_path TO "{schema}"'))
            await conn.execute(
                text(
                    "CREATE TABLE events(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    "source text NOT NULL,source_event_id text NOT NULL,account text,"
                    "category text NOT NULL DEFAULT 'generic',content_text text NOT NULL DEFAULT '',"
                    "content_extra jsonb,entity_hints jsonb NOT NULL DEFAULT '[]'::jsonb,"
                    "metadata jsonb,occurred_at timestamp NOT NULL DEFAULT now(),"
                    "received_at timestamp NOT NULL DEFAULT now(),"
                    "triage_status text NOT NULL DEFAULT 'pending',"
                    "UNIQUE(source,source_event_id))"
                )
            )
            await conn.execute(
                text(
                    "CREATE TABLE schema_migrations(version text PRIMARY KEY,note text)"
                )
            )
            await conn.execute(
                text(
                    "CREATE TABLE instagram_sessions(username text PRIMARY KEY,is_active boolean NOT NULL)"
                )
            )
            await run_migration_sql(conn, migration)
            await run_migration_sql(conn, delivery_migration)
            await run_migration_sql(conn, gmail_migration)
            await run_migration_sql(conn, protocol_migration)
        yield engine, schema
    finally:
        async with engine.begin() as conn:
            await conn.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        await engine.dispose()
