-- Additive shadow tables. No legacy events are copied or changed.
BEGIN;

CREATE TABLE IF NOT EXISTS brain_source_objects (
    provider text NOT NULL, account_id text NOT NULL,
    object_type text NOT NULL, external_id text NOT NULL,
    active_generation bigint, source_head_revision text,
    PRIMARY KEY (provider, account_id, object_type, external_id)
);

CREATE TABLE IF NOT EXISTS brain_revisions (
    provider text NOT NULL, account_id text NOT NULL,
    object_type text NOT NULL, external_id text NOT NULL,
    revision text NOT NULL, content_hash text NOT NULL,
    received_at timestamptz NOT NULL, required_scope text NOT NULL,
    deleted boolean NOT NULL, previous_revision text,
    PRIMARY KEY (provider, account_id, object_type, external_id, revision),
    FOREIGN KEY (provider, account_id, object_type, external_id)
        REFERENCES brain_source_objects(provider, account_id, object_type, external_id)
);

CREATE TABLE IF NOT EXISTS brain_revision_receipts (
    provider text NOT NULL, account_id text NOT NULL,
    object_type text NOT NULL, external_id text NOT NULL,
    revision text NOT NULL, content_text text NOT NULL,
    metadata jsonb NOT NULL, occurred_at text NOT NULL,
    payload_hash text NOT NULL, origin text NOT NULL,
    PRIMARY KEY (provider, account_id, object_type, external_id, revision),
    CHECK (origin IN ('source', 'legacy_snapshot')),
    FOREIGN KEY (provider, account_id, object_type, external_id, revision)
        REFERENCES brain_revisions(provider, account_id, object_type, external_id, revision)
);

CREATE TABLE IF NOT EXISTS brain_generations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL, account_id text NOT NULL,
    object_type text NOT NULL, external_id text NOT NULL,
    revision text NOT NULL, extraction_version text NOT NULL,
    known_from timestamptz NOT NULL, known_to timestamptz,
    UNIQUE (provider, account_id, object_type, external_id, revision, extraction_version),
    CHECK (known_to IS NULL OR known_to > known_from),
    FOREIGN KEY (provider, account_id, object_type, external_id, revision)
        REFERENCES brain_revisions(provider, account_id, object_type, external_id, revision)
);

CREATE TABLE IF NOT EXISTS brain_claims (
    generation_id bigint NOT NULL REFERENCES brain_generations(id),
    ordinal integer NOT NULL, subject text NOT NULL,
    predicate text NOT NULL, value text NOT NULL,
    valid_from timestamptz NOT NULL, valid_to timestamptz,
    evidence_anchor text NOT NULL, evidence_kind text NOT NULL,
    PRIMARY KEY (generation_id, ordinal),
    CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CHECK (evidence_kind IN ('user_report', 'document', 'inference'))
);

CREATE TABLE IF NOT EXISTS brain_checkpoints (
    provider text NOT NULL, account_id text NOT NULL, cursor text,
    PRIMARY KEY (provider, account_id)
);

CREATE TABLE IF NOT EXISTS brain_rollback_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL, account_id text NOT NULL,
    object_type text NOT NULL, external_id text NOT NULL,
    from_generation bigint NOT NULL REFERENCES brain_generations(id),
    target_generation bigint NOT NULL REFERENCES brain_generations(id),
    restored_generation bigint NOT NULL REFERENCES brain_generations(id),
    known_at timestamptz NOT NULL, reason text NOT NULL
);

CREATE TABLE IF NOT EXISTS brain_event_links (
    event_id bigint PRIMARY KEY REFERENCES events(id),
    provider text NOT NULL, account_id text NOT NULL,
    object_type text NOT NULL, external_id text NOT NULL,
    UNIQUE (provider, account_id, object_type, external_id),
    FOREIGN KEY (provider, account_id, object_type, external_id)
        REFERENCES brain_source_objects(provider, account_id, object_type, external_id)
);

CREATE TABLE IF NOT EXISTS brain_derived_cache (
    provider text NOT NULL, account_id text NOT NULL,
    cache_key text NOT NULL, payload jsonb NOT NULL,
    PRIMARY KEY (provider, account_id, cache_key)
);

CREATE INDEX IF NOT EXISTS ix_brain_generations_as_of
    ON brain_generations (provider, account_id, known_from, known_to);

INSERT INTO schema_migrations(version, note)
VALUES ('047_shadow_brain', 'additive shadow provenance, claims, audit, and legacy ID map')
ON CONFLICT (version) DO NOTHING;

COMMIT;
