-- Synthetic-only durable capture. No live connector is wired to this queue.
BEGIN;

CREATE TABLE IF NOT EXISTS brain_delivery_cursors (
    provider text NOT NULL, account_id text NOT NULL, cursor text,
    PRIMARY KEY (provider, account_id),
    CHECK (provider = 'synthetic' AND account_id = 'queue-fixture')
);

CREATE TABLE IF NOT EXISTS brain_delivery_batches (
    provider text NOT NULL, account_id text NOT NULL,
    next_cursor text NOT NULL, expected_cursor text,
    manifest jsonb NOT NULL,
    PRIMARY KEY (provider, account_id, next_cursor),
    FOREIGN KEY (provider, account_id)
        REFERENCES brain_delivery_cursors(provider, account_id)
);

CREATE TABLE IF NOT EXISTS brain_delivery_envelopes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL, account_id text NOT NULL,
    delivery_id text NOT NULL, capture_cursor text NOT NULL,
    payload jsonb NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    lease_token text, lease_until timestamptz,
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    error text,
    captured_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    UNIQUE (provider, account_id, delivery_id),
    FOREIGN KEY (provider, account_id)
        REFERENCES brain_delivery_cursors(provider, account_id),
    CHECK (provider = 'synthetic' AND account_id = 'queue-fixture'),
    CHECK (status IN ('pending', 'leased', 'done', 'quarantined')),
    CHECK ((status = 'leased') = (lease_token IS NOT NULL AND lease_until IS NOT NULL)),
    CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS ix_brain_delivery_order
    ON brain_delivery_envelopes(provider, account_id, id)
    WHERE status <> 'done';

INSERT INTO schema_migrations(version, note)
VALUES ('048_shadow_delivery', 'disabled synthetic durable delivery queue')
ON CONFLICT (version) DO NOTHING;

COMMIT;
