-- Offline Gmail contract pilot only. No live mailbox adapter is wired.
BEGIN;
CREATE TABLE IF NOT EXISTS brain_gmail_pilot_accounts (
    google_sub text PRIMARY KEY,
    display_email text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    captured_cursor text,
    applied_cursor text,
    coverage_break boolean NOT NULL DEFAULT false,
    coverage_break_at timestamptz,
    resync_required boolean NOT NULL DEFAULT false,
    CHECK (google_sub LIKE 'synthetic-%')
);
CREATE TABLE IF NOT EXISTS brain_gmail_pilot_pages (
    google_sub text NOT NULL REFERENCES brain_gmail_pilot_accounts(google_sub),
    page_id text NOT NULL,
    start_history_id text NOT NULL,
    end_history_id text NOT NULL,
    manifest jsonb NOT NULL,
    PRIMARY KEY (google_sub,page_id)
);
CREATE TABLE IF NOT EXISTS brain_gmail_pilot_resyncs (
    google_sub text NOT NULL REFERENCES brain_gmail_pilot_accounts(google_sub),
    history_id text NOT NULL,
    observed_at timestamptz NOT NULL,
    available_at timestamptz NOT NULL,
    present_ids jsonb NOT NULL,
    PRIMARY KEY (google_sub,history_id)
);
CREATE TABLE IF NOT EXISTS brain_gmail_pilot_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub text NOT NULL REFERENCES brain_gmail_pilot_accounts(google_sub),
    event_key text NOT NULL,
    resync_history_id text,
    history_id text NOT NULL,
    message_id text NOT NULL,
    kind text NOT NULL,
    fetch_state text NOT NULL DEFAULT 'pending',
    fetched_payload jsonb,
    observed_history_id text,
    observed_at timestamptz,
    error text,
    captured_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    applied_at timestamptz,
    UNIQUE (google_sub,event_key),
    CHECK (kind IN ('added','deleted','label_added','label_removed')),
    CHECK (fetch_state IN ('pending','fetched','failed','missing','forbidden',
                          'deleted_before_fetch','done','quarantined','obsolete','gap'))
);
CREATE INDEX IF NOT EXISTS ix_brain_gmail_pilot_pending
    ON brain_gmail_pilot_events(google_sub,id) WHERE fetch_state <> 'done';
CREATE INDEX IF NOT EXISTS ix_brain_gmail_pilot_resync_asof
    ON brain_gmail_pilot_resyncs(google_sub,available_at DESC);
INSERT INTO schema_migrations(version,note)
VALUES ('049_gmail_shadow_pilot','offline Gmail history contract pilot')
ON CONFLICT(version) DO NOTHING;
COMMIT;
