"""Few-shot examples for the query router LLM."""

QUERY_FEWSHOTS: list[tuple[str, dict]] = [
    (
        "Саммари за вчера?",
        {"output_shape": "SUMMARY", "operation": "SEARCH", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "YESTERDAY"},
         "query_variants": ["саммари за вчера", "итоги за вчера"], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "О чем с Евочкой говорили вчера?",
        {"output_shape": "SUMMARY", "operation": "SEARCH", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "chat_types": ["private"], "chat_query": "Евочка", "time_range": "YESTERDAY"},
         "query_variants": ["о чём говорили", "итоги переписки"], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "В чате Евочка Моя какое последнее сообщение есть?",
        {"output_shape": "LIST", "operation": "RECENT_MESSAGES", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "chat_types": ["private"], "chat_query": "Евочка Моя", "time_range": "NONE", "limit": 3},
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Покажи голосовые в чате Евочка Моя",
        {"output_shape": "LIST", "operation": "MEDIA_MESSAGES", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "chat_types": ["private"], "chat_query": "Евочка Моя", "media_type": "voice", "time_range": "LAST_30_DAYS", "limit": 20},
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Найди афишу на эту неделю на веранде",
        {"output_shape": "ANSWER", "operation": "SEARCH", "need_proof": True, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "LAST_7_DAYS"},
         "query_variants": ["афиша веранда", "расписание веранда", "veranda schedule", "афиша veranda"],
         "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "а есть чаты в базе за вчера?",
        {"output_shape": "ANALYTICS", "operation": "SEARCH", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "YESTERDAY", "limit": 50},
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Что было 5 мая?",
        {"output_shape": "SUMMARY", "operation": "SEARCH", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "LAST_30_DAYS"},
         "query_variants": ["5 мая", "05.05", "пятое мая"], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Найди упоминания \"синхронизация\" во всех чатах",
        {"output_shape": "LIST", "operation": "SEARCH", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "time_range": "ALL_TIME", "limit": 40},
         "query_variants": ["синхронизация", "sync", "synced", "синк"], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Скинь документы по проекту Dimondra",
        {"output_shape": "LIST", "operation": "MEDIA_MESSAGES", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "media_type": "document", "time_range": "ALL_TIME", "limit": 30},
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Кто больше всего писал за месяц?",
        {"output_shape": "ANALYTICS", "operation": "DYNAMIC_QUERY", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "LAST_30_DAYS"},
         "dynamic_tool": {
             "select": [{"field": "user_id", "agg": None}, {"field": "message_id", "agg": "COUNT", "as_name": "messages"}],
             "filters": [{"field": "user_id", "op": "IS_NOT_NULL", "value": True}],
             "group_by": ["user_id"],
             "order_by": [{"field": "messages", "desc": True}],
             "limit": 20,
             "require_time_range": True,
         },
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Что обсуждалось в папке Работа за неделю?",
        {"output_shape": "SUMMARY", "operation": "SEARCH", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "folder": "Работа", "time_range": "LAST_7_DAYS"},
         "query_variants": ["итоги", "что обсуждали", "summary"], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Покажи фото из чата @mychannel за 7 дней",
        {"output_shape": "LIST", "operation": "MEDIA_MESSAGES", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "chat_query": "@mychannel", "media_type": "photo", "time_range": "LAST_7_DAYS", "limit": 30},
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "В этом чате найди упоминания \"релиз\"",
        {"output_shape": "LIST", "operation": "SEARCH", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "CURRENT_CHAT", "time_range": "ALL_TIME", "limit": 30},
         "query_variants": ["релиз", "release", "deploy"], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Здесь что обсуждали вчера?",
        {"output_shape": "SUMMARY", "operation": "SEARCH", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "CURRENT_CHAT", "time_range": "YESTERDAY"},
         "query_variants": ["итоги", "что обсуждали", "summary"], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Найди мои сообщения про отпуск за 30 дней",
        {"output_shape": "LIST", "operation": "DYNAMIC_QUERY", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "time_range": "LAST_30_DAYS"},
         "dynamic_tool": {
             "select": [{"field": "chat_id", "agg": None}, {"field": "telegram_msg_id", "agg": None}, {"field": "date_utc", "agg": None}, {"field": "text_any", "agg": None}],
             "filters": [{"field": "direction", "op": "EQ", "value": "out"}, {"field": "text_any", "op": "ILIKE", "value": "отпуск"}],
             "group_by": [],
             "order_by": [{"field": "date_utc", "desc": True}],
             "limit": 50,
             "require_time_range": True,
         },
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Сколько сообщений было сегодня?",
        {"output_shape": "ANALYTICS", "operation": "DYNAMIC_QUERY", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "TODAY"},
         "dynamic_tool": {
             "select": [{"field": "message_id", "agg": "COUNT", "as_name": "messages"}],
             "filters": [],
             "group_by": [],
             "order_by": [],
             "limit": 1,
             "require_time_range": True,
         },
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Найди все чаты, кому я делал сайты",
        {"output_shape": "LIST", "operation": "CHAT_LIST", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "ALL_TIME"},
         "query_variants": ["делал сайт", "разработка сайта", "сделал сайт", "website"],
         "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "В каких чатах обсуждали оплату?",
        {"output_shape": "LIST", "operation": "CHAT_LIST", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "ALL_TIME"},
         "query_variants": ["оплата", "оплатить", "платёж", "оплачено"],
         "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Покажи все чаты где упоминается Telegram",
        {"output_shape": "LIST", "operation": "CHAT_LIST", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "ALL_TIME"},
         "query_variants": ["Telegram", "телеграм", "тг"],
         "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "а чат levaromat? там тоже было про сайт",
        {"output_shape": "LIST", "operation": "SEARCH", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "chat_query": "levaromat", "time_range": "ALL_TIME", "limit": 30},
         "query_variants": ["сайт", "сделал сайт", "разработка сайта"],
         "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "lec-telecom - в нем есть про сайт что?",
        {"output_shape": "LIST", "operation": "DYNAMIC_QUERY", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "time_range": "ALL_TIME"},
         "dynamic_tool": {
             "select": [{"field": "chat_id", "agg": None}, {"field": "telegram_msg_id", "agg": None}, {"field": "date_utc", "agg": None}, {"field": "text_any", "agg": None}, {"field": "chat_title", "agg": None}],
             "filters": [{"field": "chat_title", "op": "ILIKE", "value": "lec-telecom"}, {"field": "text_any", "op": "ILIKE", "value": "сайт"}],
             "group_by": [],
             "order_by": [{"field": "date_utc", "desc": True}],
             "limit": 30,
             "require_time_range": False,
         },
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "lec-telecom есть такой чат в базе?",
        {"output_shape": "ANSWER", "operation": "SEARCH", "need_proof": False, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "chat_query": "lec-telecom", "time_range": "NONE"},
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 1, "on_empty": "ASK_CLARIFY", "notes": None},
    ),
    (
        "о чем я говорил в чате Анна Шелест?",
        {"output_shape": "SUMMARY", "operation": "SEARCH", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "chat_query": "Анна Шелест", "time_range": "LAST_30_DAYS"},
         "query_variants": ["о чём говорили", "итоги переписки"],
         "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "В каких чатах обсуждали оплату?",
        {"output_shape": "ANALYTICS", "operation": "DYNAMIC_QUERY", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "ALL_TIME"},
         "dynamic_tool": {
             "select": [{"field": "chat_id", "agg": None}, {"field": "message_id", "agg": "COUNT", "as_name": "mentions"}],
             "filters": [{"field": "text_any", "op": "ILIKE", "value": "оплат"}],
             "group_by": ["chat_id"],
             "order_by": [{"field": "mentions", "desc": True}],
             "limit": 20,
             "require_time_range": False,
         },
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Сколько я отправил сообщений в каждый чат за месяц?",
        {"output_shape": "ANALYTICS", "operation": "DYNAMIC_QUERY", "need_proof": False, "precision_bias": "BALANCED",
         "constraints": {"scope": "ALL_CHATS", "time_range": "LAST_30_DAYS"},
         "dynamic_tool": {
             "select": [{"field": "chat_id", "agg": None}, {"field": "message_id", "agg": "COUNT", "as_name": "sent"}],
             "filters": [{"field": "direction", "op": "EQ", "value": "out"}],
             "group_by": ["chat_id"],
             "order_by": [{"field": "sent", "desc": True}],
             "limit": 30,
             "require_time_range": True,
         },
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
    (
        "Покажи все мои сообщения с упоминанием ссылок за всё время",
        {"output_shape": "LIST", "operation": "DYNAMIC_QUERY", "need_proof": True, "precision_bias": "PRECISION",
         "constraints": {"scope": "ALL_CHATS", "time_range": "ALL_TIME"},
         "dynamic_tool": {
             "select": [{"field": "chat_id", "agg": None}, {"field": "telegram_msg_id", "agg": None}, {"field": "date_utc", "agg": None}, {"field": "text_any", "agg": None}],
             "filters": [{"field": "direction", "op": "EQ", "value": "out"}, {"field": "text_any", "op": "ILIKE", "value": "http"}],
             "group_by": [],
             "order_by": [{"field": "date_utc", "desc": True}],
             "limit": 50,
             "require_time_range": False,
         },
         "query_variants": [], "subqueries": [], "clarify_question": None, "max_steps": 2, "on_empty": "RETRY", "notes": None},
    ),
]
